<?php
/**
 * @access protected
 * @author Judzhin Miles <info[woof-woof]msbios.com>
 */

namespace MSBios\Media\CPanel\Doctrine;

// Add jses
$this->headScript()
    ->prependFile($this->basePath('limitless/assets/js/plugins/forms/inputs/formatter.min.js'))
//    ->prependFile($this->basePath('limitless/assets/js/plugins/forms/styling/uniform.min.js'))
//    ->prependFile($this->basePath('limitless/assets/js/plugins/pickers/daterangepicker.js'))
//    ->prependFile($this->basePath('limitless/assets/js/plugins/ui/moment/moment.min.js'))
//    ->prependFile($this->basePath('limitless/assets/js/plugins/notifications/jgrowl.min.js'))
//    ->prependFile($this->basePath('limitless/assets/js/plugins/uploaders/fileinput.min.js'))
//    ->prependFile($this->basePath('limitless/assets/js/plugins/notifications/jgrowl.min.js'))
//    ->prependFile($this->basePath('limitless/assets/js/plugins/editors/wysihtml5/locales/bootstrap-wysihtml5.ua-UA.js'))
//    ->prependFile($this->basePath('limitless/assets/js/plugins/editors/wysihtml5/parsers.js'))
//    ->prependFile($this->basePath('limitless/assets/js/plugins/editors/wysihtml5/toolbar.js'))
//    ->prependFile($this->basePath('limitless/assets/js/plugins/editors/wysihtml5/wysihtml5.min.js'))
    ->prependFile($this->basePath('limitless/ckeditor/ckeditor.js'))
//    ->prependFile($this->basePath('cpanel/openpower.cpanel.js'))
;

/** @var \Zend\Form\Form $form */
$form = $this->form;
$form->prepare();
?>

    <div class="panel panel-flat">

        <div class="panel-body">

            <?= $this->form()->openTag($form->setAttributes([
                'class' => 'form-horizontal',
                'role' => 'form'
            ])); ?>

            <?= $this->partial('partial/element.phtml', [
                'element' => $form->get('title')
                    ->setAttributes([
                        'required' => 'required',
                        'placeholder' => $this->translate('Enter news title')
                    ]),
                'label' => $this->translate('Title')
            ]); ?>

            <?= $this->partial('partial/element.phtml', [
                'element' => $form->get('content')->setAttribute('id', 'content')
                    ->setAttributes([
                        'required' => 'required',
                        'placeholder' => $this->translate('Enter news content')
                    ]),
                'label' => $this->translate('Content')
            ]); ?>

            <?= $this->partial('partial/element.phtml', [
                'element' => $form->get('postdate')
                    ->setAttributes([
                        'required' => 'required',
                        'placeholder' => $this->translate('Choose news postdate')
                    ]),
                'label' => $this->translate('Postdate')
            ]); ?>

            <?= $this->partial('partial/element.phtml', [
                'element' => $form->get('state')
                    ->setAttributes([
                        'required' => 'required',
                        'placeholder' => $this->translate('Select news state')
                    ]),
                'label' => $this->translate('State')
            ]); ?>

            <div class="text-right">
                <button type="reset" class="btn btn-default">Reset</button>
                <button type="submit" class="btn btn-primary">
                    Submit
                    <i class="icon-arrow-right14 position-right"></i>
                </button>
            </div>

            <?= $this->form()->closeTag(); ?>
        </div>
    </div>


<?php $this->inlineScript()->captureStart(); ?>
    $('[name="postdate"]').formatter({
        pattern: '{{9999}}-{{99}}-{{99}}'
    });

    CKEDITOR.replace('content', {
        height: '250px'
    });
<?php $this->inlineScript()->captureEnd(); ?>