<?php
/**
 * @access protected
 * @author Judzhin Miles <info[woof-woof]msbios.com>
 */

namespace MSBios\Media\CPanel\Doctrine;

$this->headScript()
    ->appendFile($this->basePath('limitless/assets/js/plugins/forms/styling/switch.min.js'))
    ->appendFile($this->basePath('limitless/assets/js/plugins/forms/styling/switchery.min.js'))
    ->appendFile($this->basePath('limitless/assets/js/plugins/forms/styling/uniform.min.js'))
    ->appendFile($this->basePath('limitless/assets/js/plugins/forms/styling/uniform.min.js'));
?>

<div class="row">
    <div class="col-md-12">

        <?php if (!$this->total): ?>
            <div class="alert alert-info no-border" role="alert">
                <h4><?= $this->translate('Information message'); ?></h4>
                <p><?= $this->translate('The database is not created at the moment no news, click "Create new news" to start working with the news.'); ?></p>
                <p>
                    <?php if ($this->isAllowed($this->resourceId, 'add')): ?>
                        <a href="<?= $this->url($this->matchedRouteName, ['action' => 'add']); ?>"
                           class="btn btn-info"><?= $this->translate('Create news'); ?></a>
                    <?php endif; ?>
                </p>
            </div>
        <?php else: ?>
            <div class="panel panel-flat">

                <div class="panel-heading">
                    <h6 class="panel-title">
                        &nbsp<a class="heading-elements-toggle"><i class="icon-more"></i></a>
                    </h6>
                    <div class="heading-elements">
                        <div class="heading-btn">
                            <?= $this->form()->openTag($this->search->prepare()->setAttributes([
                                'class' => 'heading-form',
                                'method' => 'GET'
                            ]));
                            ?>
                            <div class="form-group has-feedback">
                                <?= $this->formSearch($this->search->get('q')->setAttributes([
                                    'class' => 'form-control',
                                    'placeholder' => $this->translate('Search...')
                                ])
                                ); ?>

                                <div class="form-control-feedback">
                                    <i class="icon-search4 text-size-base text-muted"></i>
                                </div>
                            </div>
                            <?= $this->form()->closeTag(); ?>

                            &nbsp;

                            <?php if ($this->isAllowed($this->resourceId, 'add')): ?>
                                <a href="<?= $this->url($this->matchedRouteName, ['action' => 'add']); ?>"
                                   class="btn btn-success"><?= $this->translate('Create new news'); ?></a>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>

                <div class="panel-body">
                    <?php if (!$this->paginator->count()) : ?>
                        <div class="alert alert-warning no-border" role="alert">
                            <h4><?= $this->translate('Information about the search result'); ?></h4>
                            <p><?= $this->translate('Nothing was found on the search criteria, try changing the search criteria.'); ?></p>
                            <p>
                                <a href="<?= $this->url($this->matchedRouteName); ?>"
                                   class="btn btn-warning"><?= $this->translate('Back to homepage'); ?></a>
                            </p>
                        </div>
                    <?php else: ?>
                        <table class="table table-striped table-hover mails m-0 table table-actions-bar">
                            <thead>
                            <tr>
                                <th width="1"></th>
                                <th><?= $this->translate('Title'); ?></th>
                                <th class="text-center"><?= $this->translate('Type'); ?></th>
                                <th class="text-center"><?= $this->translate('State'); ?></th>
                                <th><?= $this->translate('Postdate'); ?></th>
                                <th><?= $this->translate('Creator'); ?></th>
                                <th><?= $this->translate('Created At'); ?></th>
                                <th width="100px" class="text-center">
                                    <?= $this->translate('Actions'); ?>
                                </th>
                            </tr>
                            </thead>

                            <tbody>
                            <?php /** @var \MSBios\Media\Resource\Doctrine\Entity\News $item */ ?>
                            <?php foreach ($this->paginator as $item): ?>
                                <tr>
                                    <td>
                                        <a target="_blank" href="<?= $this->url('home/news/view', [
                                            'id' => $item->getId(),
                                            'slug' => $item->getSlug()
                                        ]); ?>">
                                            <i class="icon-eye4"></i>
                                        </a>
                                    </td>
                                    <td><?= $this->truncate($this->escapeHtml($item->getTitle()), 125); ?></td>
                                    <td class="text-center">
                                    <span class="label label-success">
                                        <?= $item->getType(); ?>
                                    </span>
                                    </td>
                                    <td class="text-center">
                                    <span class="label label-success">
                                        <?= $item->getState(); ?>
                                    </span>
                                    </td>
                                    <td>
                                        <?= $this->dateFormat(
                                            $item->getPostdate(),
                                            \IntlDateFormatter::MEDIUM,
                                            \IntlDateFormatter::SHORT);
                                        ?>
                                    </td>
                                    <td>
                                        <?= $this->escapeHtml($item->getCreator()->getUsername()); ?>
                                    </td>
                                    <td>
                                        <?= $this->dateFormat(
                                            $item->getCreatedAt(),
                                            \IntlDateFormatter::MEDIUM,
                                            \IntlDateFormatter::SHORT);
                                        ?>
                                    </td>
                                    <td class="text-center">

                                        <?= $this->partial('partial/actions.phtml', [
                                            'matchedRouteName' => $this->matchedRouteName,
                                            'identifier' => $item->getId()
                                        ]); ?>

                                    </td>
                                </tr>
                            <?php endforeach; ?>
                            </tbody>
                        </table>
                        <?= $this->paginationControl($this->paginator, 'sliding', 'partial/pagination.phtml', [
                            'route' => $this->matchedRouteName
                        ]); ?>
                    <?php endif; ?>
                </div>
            </div>
        <?php endif; ?>
    </div>
</div>
